### PR TITLE
Migrate to .NET-Core-SDK-RC3

### PR DESCRIPTION
**Pull request by toburger**
> Please ignore/close this pull request if you aren't planning to migrate to RC3 in brevity...

I'm quite new to dotnet core and this is my first project which "required" me to work with dotnet core (I happily ignored it since today :smile:).
I've tried to build your project but my toolset seems to be "too new" so I've migrated the project system to the current release...

I've followed Enrico Sada's guide on how to migrate a project.json file to fsproj from here:
https://github.com/dotnet/netcorecli-fsc/wiki/How-to-migrate-preview2-projects-to-rc3

`dotnet restore` doesn't work at the root directory anymore and I have no idea on howto configure the build (maybe a .sln file is needed?).

### CODE REVIEW

**Comment by dustinmoris** [comment]
Great effort, thanks for that. I will not merge or close this PR yet, because I want to find out what the migration to RC3 means in terms of tooling, compatibility and working with F# in .NET Core.

Does the F# tooling in VS 2017 already work or does Ionide work with .NET Core RC3? Can other .NET Core projects which are still on project.json continue using ASP.NET Core Lambda after upgrading to RC3? Does AppVeyor support RC3 already so it can produce official packages? etc.

Once I have figured out those things I will let you know how soon I think we merge this PR

**Comment by toburger** [comment]
From my tests I can  answer some questions, still I'm quiet new to the whole .NET Core story and it is possible that I'm making mistakes...

Do RC3 packages work with older projects: They should, since the assembly format hasn't changed, but I can't test it, so I have no idea!

VS 2017 RC3: Tooling not ready, don't know if I'm missing something


Ionide: works

Appveyor: old dotnet core version, needs a project.json file

**Comment by dustinmoris** [comment]
Ok, cool... I can help you with AppVeyor maybe. I think it should be possible to pull the RC3 SDK of dotnet in a pre-build step and set it up so that the build will work later. I will try this out tomorrow evening probably and let you know

**Comment by toburger** [comment]
cool! thank you!

**Comment by dustinmoris** [comment]
Hey, just wanted to let you know that I installed VS 2017 today and pulled this branch and started to look into things. I will try to get the appveyor build working in the next couple days and then get this merged if there's nothing else holding back.

**Comment by xdaDaveShaw** [comment]
I did some googling last night looking for any GitHub / Connect issues for this error message and couldn't find any, do we know if the FSharp team are aware of this and looking to resolve it before RTW?

**Comment by dbettin** [comment]
Yes, F# .Net Core does not work in 2017. They are aware of the issue. ‪ https://github.com/Microsoft/visualfsharp/issues/2400‬

**Comment by dustinmoris** [comment]
Hi, I had your code pulled into a local branch and worked through the remaining issues. I also upgraded to the even newer RC4 and had to make a few changes to tests to be able to successfully run them again and then the majority of the work was to figure out how to get AppVeyor builds working again. I ended up manually installing the RC4 SDK at the beginning of the build script.

You can see the exact changes in [this compare link](https://github.com/dustinmoris/AspNetCore.Lambda/compare/v0.1.0-alpha003...feature/migrate_to_rc4).

Thank you for helping me with this and in this case I will close the PR without merging it as it doesn't make sense at this point anymore.

**Comment by toburger** [comment]
Wow! Cool! Didn't notice that there is now a RC4...

**Comment by sergey-tihon** [comment]
@toburger you can copy-parse from here https://github.com/fsprojects/FsUnit/pull/100/files (if any)
CI / new FSharp.Cope, no need for dotnet-compile-fsc and etc

**Pull request closed without merging**
